name: CI

on:
  push:
    branches:
    - master

env:
  PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
  RUN_REGION: us-central1
  SERVICE_NAME: personal-webserver

jobs:
  buildploy:
    name: buildploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      # Setup gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '275.0.0'
          service_account_email: ${{ secrets.GOOGLE_SA_EMAIL }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      # Configure gcloud CLI
      - name: gcloud Set up
        run: |
          gcloud config set project $PROJECT_ID
          gcloud config set run/region $RUN_REGION
      # Build and push image to Google Container Registry
      - name: Build
        run: |
          gcloud builds submit -t gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA
      # Deploy image to Cloud Run
      - name: Deploy
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA \
            --platform managed \
            --allow-unauthenticated
