name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build and Push
      uses: zemuldo/docker-build-push@master
      env:
        GCLOUD_PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
        GCLOUD_AUTH: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        REGISTRY_URL: "gcr.io"
      with:
       image_name: "mattprestlien/personal-webserver"
       image_tag: "latest"
